import pw from '/home/claude/.npm-global/lib/node_modules/playwright/index.js';
const { chromium } = pw;
const b = await chromium.launch({ executablePath:'/opt/pw-browsers/chromium' });
const p = await b.newPage({ viewport:{ width:1500, height:1000 } });
const errs=[]; p.on('pageerror',e=>errs.push('pageerror: '+e.message));
p.on('console',m=>{ if(m.type()==='error' && !/ERR_TUNNEL|fonts.googleapis/.test(m.text())) errs.push(m.text()); });
const say=(n,c)=>console.log((c?'  ok  ':'FAIL  ')+n);
const U='file://'+process.cwd()+'/dist/index.html';

await p.goto(U+'#/event');
await p.waitForSelector('.ecp .bar', {timeout:8000});
say('record page mounted', true);
await p.waitForTimeout(600);
say('header counters filled', /\d/.test(await p.locator('#ecp-conf').textContent()));
say('overview: rooms + team tables', (await p.locator('.ecp table.d').count())>=2);
await p.screenshot({path:'s1-overview.png'});

await p.click('.ecp .tabs button[data-t="Contacts"]');
await p.waitForSelector('#c-tw table', {timeout:8000});
const total = +(await p.locator('#c-all').textContent());
say('contacts loaded in pages ('+total+')', total>200);
say('load line mentions pages', /pages/.test(await p.locator('#c-load').textContent()));
await p.click('#c-chips button[data-k="target"]');
await p.waitForTimeout(200);
const shown = +(await p.locator('#c-shown').textContent());
say('chip filter narrows ('+shown+' of '+total+')', shown>0 && shown<total);
await p.click('#c-view button[data-v="full"]');
await p.waitForTimeout(200);
say('full view adds columns', (await p.locator('#c-tw thead th').count())>=10);
await p.screenshot({path:'s2-contacts.png'});
await p.click('#c-chips button[data-k="target"]');

await p.click('.ecp .tabs button[data-t="Meetings"]');
await p.waitForSelector('#m-tw table', {timeout:8000});
const mAll = +(await p.locator('#m-all').textContent());
say('meetings loaded ('+mAll+')', mAll>10);
say('hours counter computed', +(await p.locator('#m-hrs').textContent())>0);
await p.click('#m-chips button[data-k="recap"]'); await p.waitForTimeout(200);
say('recap filter works', +(await p.locator('#m-shown').textContent())<mAll);
await p.click('#m-chips button[data-k="recap"]');
await p.screenshot({path:'s3-meetings.png'});

// wizard
await p.click('.ecp .acts button[data-a="meeting"]');
await p.waitForSelector('.ecp-mod', {timeout:5000});
say('wizard opens blocked', await p.locator('#w-next').isDisabled());
say('blocker names the reason', /account/i.test(await p.locator('#w-msg').textContent()));
await p.fill('#w-acc','No');
await p.waitForTimeout(300);
const hits = await p.locator('#w-hits .room').count();
say('account search returns hits ('+hits+')', hits>0);
await p.locator('#w-hits .room').first().click();
await p.waitForTimeout(200);
await p.click('#w-next');
await p.waitForSelector('#w-buyers', {timeout:5000});
await p.waitForTimeout(400);
say('step 2 blocked until a buyer is picked', await p.locator('#w-next').isDisabled());
const buyer = p.locator('#w-buyers button[data-id]').first();
if (await buyer.count()) await buyer.click();
await p.locator('#w-team button').first().click();
await p.waitForTimeout(200);
say('step 2 unblocks', !(await p.locator('#w-next').isDisabled()));
await p.click('#w-next');
await p.waitForSelector('#w-rooms', {timeout:5000});
say('step 3 shows rooms with capacity', /people/.test(await p.locator('#w-rooms .room .mt').first().textContent()));
await p.click('#w-next');
await p.waitForSelector('#w-slots .slot', {timeout:8000});
const slots = await p.locator('#w-slots .slot').count();
say('availability computed ('+slots+' suggestions)', slots>0);
await p.screenshot({path:'s4-wizard.png'});
await p.locator('#w-slots .slot:not(.busy)').first().click();
await p.waitForTimeout(200);
await p.click('#w-next');
await p.waitForSelector('.kvs', {timeout:5000});
say('review lists the campaign time zone', /zone/i.test(await p.locator('.kvs').textContent()));
await p.click('#w-next');
await p.waitForSelector('.res .tickbig', {timeout:6000});
say('booking wrote a record', /Record \d+ created/.test(await p.locator('.res').textContent()));
await p.screenshot({path:'s5-booked.png'});
await p.click('#w-close');
await p.waitForTimeout(600);
say('new meeting appears in the tab', +(await p.locator('#m-all').textContent()) === mAll+1);

// 15-min grid path + blocked reasons
await p.click('.ecp .acts button[data-a="meeting"]');
await p.waitForSelector('.ecp-mod');
await p.fill('#w-acc','No'); await p.waitForTimeout(300);
await p.locator('#w-hits .room').first().click(); await p.click('#w-next');
await p.waitForSelector('#w-buyers'); await p.waitForTimeout(400);
const bb = p.locator('#w-buyers button[data-id]').first();
if (await bb.count()) await bb.click();
await p.locator('#w-team button').first().click(); await p.click('#w-next');
await p.waitForSelector('#w-rooms'); await p.click('#w-next');
await p.waitForSelector('#w-slots .slot');
await p.click('#w-mode button[data-m="grid"]'); await p.waitForTimeout(300);
const busy = await p.locator('#w-slots .slot.busy').count();
say('grid marks blocked slots with a reason ('+busy+')', busy>0);
say('reason text present', /taken|busy/.test(await p.locator('#w-slots').textContent()));

say('no console errors ('+errs.length+')', errs.length===0);
if(errs.length) console.log(errs.slice(0,4).join('\n'));
await b.close();
