import { chromium, launchOpts } from './test/browser.mjs';
const b = await chromium.launch({ ...launchOpts });
const p = await b.newPage({ viewport:{ width:1500, height:1050 } });
const errs=[]; p.on('pageerror',e=>errs.push('pageerror: '+e.message));
p.on('console',m=>{ if(m.type()==='error' && !/ERR_TUNNEL|fonts.googleapis/.test(m.text())) errs.push(m.text()); });
const say=(n,c)=>console.log((c?'  ok  ':'FAIL  ')+n);
const U='file://'+process.cwd()+'/dist/index.html';
p.on('dialog', d => d.dismiss());

/* --- room schedule --- */
await p.goto(U+'#/event');
await p.waitForSelector('.ecp .tabs button[data-t="Room schedule"]', {timeout:8000});
await p.click('.ecp .tabs button[data-t="Room schedule"]');
await p.waitForSelector('.ecp .blk', {timeout:8000});
await p.waitForTimeout(800);
const blks = await p.locator('.ecp .blk').count();
say('schedule: blocks drawn ('+blks+')', blks>3);
say('schedule: all revealed', (await p.locator('.ecp .blk.in').count())===blks);
say('schedule: now-line present', (await p.locator('.ecp .now').count())>0);
const heights = await p.$$eval('.ecp .blk', n=>n.map(x=>parseFloat(x.style.height)));
say('schedule: height tracks duration', new Set(heights).size>1);
const widths = await p.$$eval('.ecp .blk', n=>n.map(x=>x.style.width));
say('schedule: overlaps split into lanes', widths.some(w=>!w.includes('100%')));
const clashN = +(await p.locator('#v-c').textContent());
say('schedule: clash alert counted ('+clashN+')', clashN>0);
await p.click('#v-clash'); await p.waitForTimeout(700);
say('schedule: clash filter narrows', (await p.locator('.ecp .blk').count())<blks);
await p.screenshot({path:'b1-schedule.png'});
await p.click('#v-clash');

/* --- mobile board --- */
await p.goto(U+'#/rec/board');
await p.waitForSelector('.phone .card', {timeout:8000});
await p.waitForTimeout(700);
say('board: phone frame rendered', (await p.locator('.phone').count())===1);
const cards = await p.locator('.eb .card').count();
say('board: room groups with cards ('+cards+')', cards>0);
say('board: pills show counters', /meetings/.test(await p.locator('#b-pills').textContent()));
await p.click('#b-tabs button[data-t="Team"]'); await p.waitForTimeout(400);
say('board: team tab shows load bars', (await p.locator('.eb .bar2 i').count())>0);
await p.click('#b-tabs button[data-t="Meetings"]'); await p.waitForTimeout(400);
say('board: meetings tab lists the day', (await p.locator('.eb .card').count())>0);
const clashPill = p.locator('#b-pills button[data-k="clash"]');
const before = await p.locator('.eb .card').count();
await clashPill.click(); await p.waitForTimeout(400);
const after = await p.locator('.eb .card').count();
say('board: clash pill filters ('+before+' -> '+after+')', after>0 && after<before);
await clashPill.click(); await p.waitForTimeout(300);

await p.locator('.eb .card').first().click();
await p.waitForSelector('#b-recap', {timeout:5000});
await p.waitForTimeout(400);
say('board: sheet slides up', await p.locator('#b-sheet').evaluate(n=>n.classList.contains('on')));
say('board: account snapshot tiles', (await p.locator('.eb .tile').count())>=6);
await p.fill('#b-recap','they want the certification plan first. we send a scope on friday.');
await p.click('#b-ai'); await p.waitForTimeout(600);
const rew = await p.inputValue('#b-recap');
say('board: rephrase rewrote server-side', /^Outcome:/.test(rew));
say('board: undo offered', /Undo/.test(await p.locator('#b-ai').textContent()));
await p.click('#b-ai'); await p.waitForTimeout(200);
say('board: undo restores the draft', (await p.inputValue('#b-recap')).startsWith('they want'));
await p.click('#b-save'); await p.waitForTimeout(700);
say('board: recap saved to the record', /Saved/.test(await p.locator('#b-msg').textContent()));
await p.screenshot({path:'b2-board.png'});
await p.click('#b-x'); await p.waitForTimeout(400);
say('board: sheet closes', !(await p.locator('#b-sheet').evaluate(n=>n.classList.contains('on'))));
await p.click('#b-ver'); await p.waitForTimeout(400);
say('board: on-screen console opens', await p.locator('#b-console').evaluate(n=>n.classList.contains('on')));
const logTxt = await p.locator('#b-log').textContent();
say('board: console carries real entries', /coql/.test(logTxt) && /save/.test(logTxt));
await p.screenshot({path:'b3-console.png'});

say('no console errors ('+errs.length+')', errs.length===0);
if(errs.length) console.log(errs.slice(0,5).join('\n'));
await b.close();
