/* Card thumbnails for the interactive examples.

   Every example card and the three gallery tiles in the experience block show a
   strip of the screen they open. The strips are generated from the built site
   rather than drawn: run this after `npm run build` and the cards match what a
   visitor actually gets.

   Chromium renders at deviceScaleFactor 0.5, so a 1240x470 CSS-pixel clip comes
   out as a 620x235 JPEG — twice the width a card displays it at, and small
   enough that nine of them cost well under a third of a megabyte inlined.

   Run: npm run build && node tools/thumbs.mjs        (writes src/shots.js)
*/
import { chromium, launchOpts } from '../test/browser.mjs';
import { writeFileSync } from 'node:fs';

/* Every example mounts its widget into one of four hosts; the prose above it —
   the lead and "What to try" — is not what the card should show. */
const HOST = '#ecp-host, #rec-host, #oh-host, #aj-host';
const SHOTS = ['event','solution','board','enrichment','cockpit','orghealth','chat-tracker','chat-recap','agent-journal'];

const W = 1240, H = 470;
const b = await chromium.launch({ ...launchOpts });
const ctx = await b.newContext({ viewport:{ width:1280, height:1000 }, deviceScaleFactor:0.5, reducedMotion:'reduce' });
const p = await ctx.newPage();
const out = {};

for (const id of SHOTS) {
  await p.goto('file://' + process.cwd() + '/dist/index.html#/p/' + id);
  /* The host div exists before the widget fills it, so wait for the height as
     well as the element — otherwise the card gets a photograph of a spinner. */
  await p.waitForSelector(HOST, { timeout: 15000 }).catch(()=>{});
  await p.waitForFunction(sel => {
    const h = document.querySelector(sel); return h && h.getBoundingClientRect().height > 420;
  }, HOST, { timeout: 20000 }).catch(()=>{});
  await p.waitForTimeout(1200);
  const box = await p.evaluate(sel => {
    const host = document.querySelector(sel); if (!host) return null;
    const r = host.getBoundingClientRect();
    return { x: Math.round(r.left + window.scrollX), y: Math.round(r.top + window.scrollY),
             w: Math.round(r.width), h: Math.round(r.height) };
  }, HOST);
  if (!box || box.h < 120) { console.log('FAIL  ' + id + ': no widget to photograph'); process.exitCode = 1; continue; }
  const clip = { x: box.x, y: box.y, width: Math.min(box.w, W), height: Math.min(box.h, H) };
  /* The widget sits below the fold on every one of these pages, and a clip
     without fullPage is intersected with the viewport — which is how an earlier
     version of this script produced nine 44-pixel slivers. */
  const buf = await p.screenshot({ clip, fullPage:true, type:'jpeg', quality:70 });
  out[id] = 'data:image/jpeg;base64,' + buf.toString('base64');
  console.log('  ok  ' + id.padEnd(14) + String(Math.round(buf.length/1024)).padStart(4) + ' KB');
}
await b.close();

const total = Object.values(out).reduce((n,v)=>n+v.length,0);
writeFileSync('src/shots.js',
  '/* Generated by tools/thumbs.mjs — do not edit by hand.\n'
+ '   A strip of each interactive example, shown on its card. Regenerate with\n'
+ '   `npm run build && node tools/thumbs.mjs` whenever a screen changes. */\n'
+ 'window.SHOTS = {\n'
+ Object.entries(out).map(([k,v]) => "  '" + k + "': '" + v + "'").join(',\n')
+ '\n};\n');
console.log('\nsrc/shots.js written — ' + Object.keys(out).length + ' thumbnails, ' + Math.round(total/1024) + ' KB inlined');
